module.exports = {
  theme: {
    extend: {
      fontSize: {
        tiny: ['12px', '18px'],
        tiny2: ['0.85rem', '1rem'],
        small: ['14px', '18px'],
        small2: ['14px', '16px'],
        small3: ['16px', '19px'],
        mid: ['32px', '37px'],
        xss: '.55rem',
      },
      width: {
        '11.5/12': '95%',
        629: '629px',
      },
      spacing: {
        72: '18rem',
        84: '21rem',
        96: '24rem',
        80: '20rem',
      },
      maxWidth: {
        '7xl': '80rem',
        '8xl': '90rem',
        629: '629px',
      },
      boxShadow: {
        'custom-main': '0px 4px 3px rgba(0, 0, 0, 0.05)',
        'custom-main-2': '0px 2px 3px rgba(0, 0, 0, 0.1)',
      },
      margin: {
        9: '2.125rem',
        '0-2': '0.2px',
      },
      inset: {
        0: 0,
        12: '3rem',
        64: '16rem',
        '1/5': '20%',
      },
      colors: {
        'custom-dark': '#363740',
        'custom-blue': '#007AFF',
        'custom-blue-2': '#3554D1',
        // 'custom-blue-3': '#3e59cc',
        'custom-blue-3': '#3554D1',
        'custom-blue-light': 'rgba(53, 84, 209, 0.08)',
        'custom-blue-lighter': '#e7f2ff',
        'custom-dark-lighter': '#A4A6B3',
        'custom-dark-lighter-2': 'rgba(159,162,180, 0.1)',
        'custom-dark-lighter-3': '#96A0B5',
        'custom-dark-lighter-4': '#f3f3f3',
        'custom-black': '#121F3E',
        'custom-gray-bg': '#fafafb',
        'custom-gray-lighter': '#F2F5FD',
        regalBlue: {
          200: '#3554D1',
          300: '#2D47B0',
          400: '#121F3E',
          500: 'rgba(53, 84, 209, 0.06)',
          600: '#f2f5fd',
          700: '#007aff',
        },
        grey: {
          100: '#96A0B5',
          200: '#E5EBF0',
          300: '#121F3E',
          400: '#363740',
          500: '#9FA2B4',
          600: '#dfe0eb',
          700: '#a4a6b3',
        },
        customPurple: {
          100: '#9013fe',
          200: '#390963',
        },
        customGreen: {
          100: '#16c18e',
        },
        customRed: {
          100: '#f03738',
        },
      },
      fontFamily: {
        firma: 'BR Firma Regular',
        'firma-italic': 'BR Firma Regular Italic',
        'firma-thin': 'BR Firma Thin',
        'firma-thin-italic': 'BR Firma Thin Italic',
        'firma-extralight': 'BR Firma ExtraLight',
        'firma-extralight-italic': 'BR Firma ExtraLight Italic',
        'firma-light': 'BR Firma Light',
        'firma-light-italic': 'BR Firma Light Italic',
        'firma-medium': 'BR Firma Medium',
        'firma-medium-italic': 'BR Firma Medium Italic',
        'firma-semibold': 'BR Firma SemiBold',
        'firma-semibold-italic': 'BR Firma SemiBold Italic',
        'firma-bold': 'BR Firma Bold',
        'firma-bold-italic': 'BR Firma Bold Italic',
        'firma-black': 'BR Firma Black',
        'firma-black-italic': 'BR Firma Black Italic',
      },
      fontWeight: {
        hairline: 100,
        'extra-light': 100,
        thin: 200,
        light: 300,
        normal: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
        extrabold: 800,
        'extra-bold': 800,
        black: 900,
      },
    },
  },
  variants: {},
  plugins: [require('@tailwindcss/forms')],
  purge: {
    enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
    ],
  },
}
